export interface BingoSong {
  title: string;
  artist: string;
}

export const BINGO_SONGS: BingoSong[] = [
  { title: 'La Perla', artist: 'ROSALÍA, Yahritza Y Su Esencia' },
  { title: 'FAVORITA', artist: 'Angela Torres' },
  { title: 'Beauty And A Beat', artist: 'Justin Bieber, Nicki Minaj' },
  { title: 'Best Song Ever', artist: 'One Direction' },
  { title: 'Zoo - From "Zootopia 2"', artist: 'Disney, Shakira' },
  { title: 'APT.', artist: 'ROSÉ, Bruno Mars' },
  { title: 'Las Jordans', artist: 'TINI' },
  { title: 'Heathens', artist: 'Twenty One Pilots' },
  { title: 'Believer', artist: 'Imagine Dragons' },
  { title: 'Blinding Lights', artist: 'The Weeknd' },
  { title: '24K Magic', artist: 'Bruno Mars' },
  { title: 'Party In The U.S.A.', artist: 'Miley Cyrus' },
  { title: 'RAMEN PARA DOS', artist: 'Maria Becerra, Paulo Londra, XROSS' },
  { title: 'Tal Vez', artist: 'Paulo Londra' },
  { title: 'Me Rehúso', artist: 'Danny Ocean' },
  { title: 'Problem', artist: 'Ariana Grande, Iggy Azalea' },
  { title: 'Un Año Sin Lluvia', artist: 'Selena Gomez & The Scene' },
  { title: 'See You Again (feat. Charlie Puth)', artist: 'Wiz Khalifa, Charlie Puth' },
  { title: 'Summer', artist: 'Calvin Harris' },
  { title: 'Umbrella', artist: 'Rihanna, JAŸ-Z' },
  { title: 'Stitches', artist: 'Shawn Mendes' },
  { title: 'STAY (with Justin Bieber)', artist: 'The Kid LAROI, Justin Bieber' },
  { title: 'REAL GANGSTA LOVE', artist: 'Trueno' },
  { title: 'Malbec', artist: 'Duki, Bizarrap' },
  { title: 'Quevedo: Bzrp Music Sessions, Vol. 52/66', artist: 'Bizarrap, Quevedo' },
  { title: 'HOLA PERDIDA', artist: 'Luck Ra, KHEA' },
  { title: 'BIRDS OF A FEATHER', artist: 'Billie Eilish' },
  { title: 'Levitating', artist: 'Dua Lipa' },
  { title: 'Manchild', artist: 'Sabrina Carpenter' },
  { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys' },
  { title: 'End of Beginning', artist: 'Djo' },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen' },
  { title: 'In the Name of Love', artist: 'Martin Garrix, Bebe Rexha' },
  { title: 'Closer', artist: 'The Chainsmokers, Halsey' },
  { title: 'Sucker', artist: 'Jonas Brothers' },
  { title: 'BESO', artist: 'ROSALÍA, Rauw Alejandro' },
  { title: 'Blank Space', artist: 'Taylor Swift' },
  { title: 'Tutu', artist: 'Camilo, Pedro Capó' },
  { title: 'No Se Va', artist: 'Morat' },
  { title: 'Tusa', artist: 'KAROL G, Nicki Minaj' },
  { title: 'Ojitos Lindos', artist: 'Bad Bunny, Bomba Estéreo' },
  { title: 'Los del Espacio', artist: 'LIT killah, Tiago PZK, Maria Becerra, Duki, Emilia, Rusherking, Big One, FMK' },
  { title: "Pa' la Selección", artist: 'La T y La M' },
  { title: 'Sorry', artist: 'Justin Bieber' },
  { title: 'Tiroteo - Remix', artist: 'Marc Seguí, Rauw Alejandro, Pol Granch' }
];
