export interface BingoSong {
  title: string;
  artist: string;
  youtubeId?: string;
}

export const BINGO_SONGS: BingoSong[] = [
  { title: 'La Perla', artist: 'ROSALÍA, Yahritza Y Su Esencia', youtubeId: 'mUuTNu6N1Bw' },
  { title: 'FAVORITA', artist: 'Angela Torres', youtubeId: '9-rFp4_xKns' },
  { title: 'Beauty And A Beat', artist: 'Justin Bieber, Nicki Minaj', youtubeId: 'PfAWReB9Spw' },
  { title: 'Best Song Ever', artist: 'One Direction', youtubeId: 'o_v9MY_FMcw' },
  { title: 'Zoo - From "Zootopia 2"', artist: 'Disney, Shakira', youtubeId: 'wQ_POfToaHQ' },
  { title: 'APT.', artist: 'ROSÉ, Bruno Mars', youtubeId: 'ekr2nIex040' },
  { title: 'Las Jordans', artist: 'TINI', youtubeId: 'K7Z6Y0q9H-s' },
  { title: 'Heathens', artist: 'Twenty One Pilots', youtubeId: 'UprcpdwuwCg' },
  { title: 'Believer', artist: 'Imagine Dragons', youtubeId: '7wtfhZwyrcc' },
  { title: 'Blinding Lights', artist: 'The Weeknd', youtubeId: '4NRXx6U8ABQ' },
  { title: '24K Magic', artist: 'Bruno Mars', youtubeId: 'UqyT8S02Hq8' },
  { title: 'Party In The U.S.A.', artist: 'Miley Cyrus', youtubeId: 'M1QHGSckqcI' },
  { title: 'RAMEN PARA DOS', artist: 'Maria Becerra, Paulo Londra, XROSS', youtubeId: 'tYtUjLpXb4A' },
  { title: 'Tal Vez', artist: 'Paulo Londra', youtubeId: '1B313jXq2i4' },
  { title: 'Me Rehúso', artist: 'Danny Ocean', youtubeId: 'aDCcLQto5BM' },
  { title: 'Problem', artist: 'Ariana Grande, Iggy Azalea', youtubeId: 'iS1g8G_njx8' },
  { title: 'Un Año Sin Lluvia', artist: 'Selena Gomez & The Scene', youtubeId: 'mS-8Psh2cCc' },
  { title: 'See You Again (feat. Charlie Puth)', artist: 'Wiz Khalifa, Charlie Puth', youtubeId: 'RgKAFK5djSk' },
  { title: 'Summer', artist: 'Calvin Harris', youtubeId: 'ebXbLfAaSrE' },
  { title: 'Umbrella', artist: 'Rihanna, JAŸ-Z', youtubeId: 'RB-W0lp0M2I' },
  { title: 'Stitches', artist: 'Shawn Mendes', youtubeId: 'dT2owtxkU8k' },
  { title: 'STAY (with Justin Bieber)', artist: 'The Kid LAROI, Justin Bieber', youtubeId: 'kTJczUoc26U' },
  { title: 'REAL GANGSTA LOVE', artist: 'Trueno', youtubeId: 'v4zR_wVpLgM' },
  { title: 'Malbec', artist: 'Duki, Bizarrap', youtubeId: '1HwqCq08L_A' },
  { title: 'Quevedo: Bzrp Music Sessions, Vol. 52/66', artist: 'Bizarrap, Quevedo', youtubeId: 'A_g3swbJ8pE' },
  { title: 'HOLA PERDIDA', artist: 'Luck Ra, KHEA', youtubeId: 'CnuFA6PkOT8' },
  { title: 'BIRDS OF A FEATHER', artist: 'Billie Eilish', youtubeId: 'fE2h3lGlO_Q' },
  { title: 'Levitating', artist: 'Dua Lipa', youtubeId: 'TUVcZfVVP3k' },
  { title: 'Manchild', artist: 'Sabrina Carpenter', youtubeId: 'xlsdJeeoH14' },
  { title: 'I Wanna Be Yours', artist: 'Arctic Monkeys', youtubeId: 'St79WmqDjsI' },
  { title: 'End of Beginning', artist: 'Djo', youtubeId: 'oXSw8DGjf5E' },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', youtubeId: 'fWNaR-rxAic' },
  { title: 'In the Name of Love', artist: 'Martin Garrix, Bebe Rexha', youtubeId: 'RnBTk8VZu00' },
  { title: 'Closer', artist: 'The Chainsmokers, Halsey', youtubeId: 'PT2_F-1esPk' },
  { title: 'Sucker', artist: 'Jonas Brothers', youtubeId: '8dMiB-nMiUM' },
  { title: 'BESO', artist: 'ROSALÍA, Rauw Alejandro', youtubeId: 'R_R9d8G4t9I' },
  { title: 'Blank Space', artist: 'Taylor Swift', youtubeId: 'e-ORhEE9VVg' },
  { title: 'Tutu', artist: 'Camilo, Pedro Capó', youtubeId: '5AkDqm-cEgg' },
  { title: 'No Se Va', artist: 'Morat', youtubeId: 'iT_s23g2jW0' },
  { title: 'Tusa', artist: 'KAROL G, Nicki Minaj', youtubeId: 'tbneQDc2V3I' },
  { title: 'Ojitos Lindos', artist: 'Bad Bunny, Bomba Estéreo', youtubeId: 'wAjHQXrIj9o' },
  { title: 'Los del Espacio', artist: 'LIT killah, Tiago PZK, Maria Becerra, Duki, Emilia, Rusherking, Big One, FMK', youtubeId: 'eBSQug_xtwc' },
  { title: "Pa' la Selección", artist: 'La T y La M', youtubeId: 'SYjD3nJTJow' },
  { title: 'Sorry', artist: 'Justin Bieber', youtubeId: 'fRh_vgS2dFE' },
  { title: 'Tiroteo - Remix', artist: 'Marc Seguí, Rauw Alejandro, Pol Granch', youtubeId: 'VEfkNHTjgs8' }
];
